{
 "title": "Otus-crud",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, exported_endpoint) (rate(http_requests_received_total{exported_endpoint!=\"/health\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(method, exported_endpoint, le) (rate(http_request_duration_seconds_bucket{exported_endpoint!=\"/health\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(method, exported_endpoint, le) (rate(http_request_duration_seconds_bucket{exported_endpoint!=\"/health\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(method, exported_endpoint, le) (rate(http_request_duration_seconds_bucket{exported_endpoint!=\"/health\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(method, exported_endpoint, le) (rate(http_request_duration_seconds_bucket{exported_endpoint!=\"/health\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}